name: Push-to-EC2
on:
  push:
    branches:
      - main
    
    
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the files
      uses: actions/checkout@v3

    - name: Copy files with SSH
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "./"
        REMOTE_HOST: "ec2-34-201-92-224.compute-1.amazonaws.com"
        REMOTE_USER: "ec2-user"
        TARGET: "/home/ec2-user/mytools"
        EXCLUDE: "/dist/, /node_modules/, **.env, rebuild_app.sh, watcher.sh"
    
    - name: Restart Docker-compose
      uses: appleboy/ssh-action@master
      with:
        host: "ec2-34-201-92-224.compute-1.amazonaws.com"
        username: "ec2-user"
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/mytools
          sudo docker-compose down
          sudo docker-compose up -d
  